```{r}
## All the linrary used for this task.
library(matlib)
library(ggplot2)
library(rsample)
library(tidymodels)

# Importing X data
X=as.matrix(read.csv(file="D:/Masters/R Lab/Lab 2/X_data.csv",header = F))
colnames(X)<-c("X1","X2","X3","X4")

# Importing Y data
Y=as.matrix(read.csv(file="D:/Masters/R Lab/Lab 2/Y_data.csv",header = F))
colnames(Y)<-c("Y")

# Importing Time data
Time = read.csv("D:/Masters/R Lab/Lab 2/time_data.csv", header = F, skip = 1)
Time = as.matrix(rbind(0, Time))

#Defining the value of X and Y against time for timeseries plot.
X.ts<-ts(X,start = c(min(Time),max(Time)),frequency =1)
Y.ts<-ts(Y,start = c(min(Time),max(Time)),frequency =1)
#Plotting those graphs
plot(X.ts,main = "Time series plot of X Signal", xlab = "Time", ylab = "Input signal", col="red")
```
```{r}
plot(Y.ts,main = "Time series plot of Y Signal", xlab = "Time", ylab = "Output signal", col="forestgreen")
```
```{r}
##Task 1: Creating a density plot with the help of histogram
#Creating a density if X signal
dis=density(X)
plot(dis,main = "Density plot of whole input signal", col="red", lwd=1.5)
polygon(dis, col = rgb(1, 0, 0, alpha = 0.5))
```

```{r}
# Creating a Histogram of X signal--different output
hist(X,freq = FALSE,main = "Histogram & Density",prob = TRUE, col = 4, density=25,angle=20, border = 4)
#Adding density in the histogram
lines(dis,lwd=2,col="maroon")
rug(jitter(X))
```
```{r}
#Creating a density if X1 signal
dis_X1=density(X[,"X1"])
hist(X[,"X1"],freq = FALSE,main = "Histogram and density plot of X1",xlab = "X1 Signal",prob = TRUE, col = "#B3E0A6", border = "#24693D")
lines(dis_X1,lwd=2,col="#B84423")
# Add the data-poins with noise in the X-axis
rug(jitter(X[,"X1"]))
```
```{r}
#Creating a density if X2 signal --different output
dis_X2=density(X[,"X2"])
hist(X[,"X2"],freq = FALSE,main = "Histogram and density plot of X2",xlab = "X1 Signal",prob = TRUE, col = "#B3E0A6", border = "#24693D")
lines(dis_X2,lwd=2,col="#B84423")
# Add the data-poins with noise in the X-axis
rug(jitter(X[,"X2"]))

```
```{r}
#Creating a density if X3 signal--different output
dis_X3=density(X[,"X3"])
hist(X[,"X3"],freq = FALSE,main = "Histogram and density plot of X3",xlab = "X3 Signal", prob = TRUE, col = "#B3E0A6", border = "#24693D")
lines(dis_X3,lwd=2,col="#B84423")
rug(jitter(X[,"X3"]))
```
```{r}
#Creating a density if X5=4 signal
dis_X4=density(X[,"X4"])
hist(X[,"X4"],freq = FALSE,main = "Histogram and density plot of X4",xlab = "X4 Signal", prob = TRUE, col = "#B3E0A6", border = "#24693D")
lines(dis_X1,lwd=2,col="#B84423")
rug(jitter(X[,"X4"]))
```
```{r}
#Creating a density if Y signal --different output
dis_y=density(Y)
plot(dis_y,main = "Density plot of Y",xlab = "Output Signal", col="#B3E0A6", lwd="2")
polygon(dis_y, col = rgb(1, 0, 1, alpha = 0.5))
```
```{r}
hist(Y,freq = FALSE,main = "Histogram and density plot of Y",xlab = "Output Signal",prob = TRUE, col = "#E65100", density=25,angle=20, border = "#E65100")
lines(dis_y,lwd=2,col="#0E3F5C")
rug(jitter(Y))
```
```{r}
## Task 1: Creating Correlation and Scatter plot.
group <- group <- ifelse(X < 0, "Group 1",
                 ifelse(X > 1, "Group 2",
                        "Group 3"))
colors <- c("#FDAE61", # Orange
            "#D9EF8B", # Light green
            "#66BD63") # Darker green
# Plotting X1 against Y--different output
plot(X[,"X1"],Y,main = "Correlation between X1 and Y signal", xlab = "X1 signal", ylab = "Output signal", pch = 19, col = colors[factor(group)])
#plot(X[,"X1"],Y,main = "Correlation between X1 and Y signal", xlab = "X1 signal", ylab = "Output signal", col="red")
```
```{r}
# Plotting X2 against Y--different output
group <- group <- ifelse(X < 0, "Group 1",
                 ifelse(X > 1, "Group 2",
                        "Group 3"))
colors <- c("#FDAE61", # Orange
            "#D9EF8B", # Light green
            "#66BD63") # Darker green
# Plotting X2 against Y--different output
plot(X[,"X2"],Y,main = "Correlation between X2 and Y signal", xlab = "X2 signal", ylab = "Output signal", pch = 19, col = colors[factor(group)])
#plot(X[,"X2"],Y,main = "Correlation betweeen X2 and Y signal", xlab = "X2 signal", ylab = "Output signal", col="red")
```
```{r}
# Plotting X3 against Y--different output
group <- group <- ifelse(X < 0, "Group 1",
                 ifelse(X > 1, "Group 2",
                        "Group 3"))
colors <- c("#FDAE61", # Orange
            "#D9EF8B", # Light green
            "#66BD63") # Darker green
# Plotting X3 against Y--different output
plot(X[,"X3"],Y,main = "Correlation between X3 and Y signal", xlab = "X3 signal", ylab = "Output signal", pch = 19, col = colors[factor(group)])
#plot(X[,"X3"],Y,main = "Correlation betweeen X3 and Y signal", xlab = "X3 signal", ylab = "Output signal", col="red")
```


```{r}
# Plotting X4 against Y--different output
group <- group <- ifelse(X < 0, "Group 1",
                 ifelse(X > 1, "Group 2",
                        "Group 3"))
colors <- c("#FDAE61", # Orange
            "#D9EF8B", # Light green
            "#66BD63") # Darker green
# Plotting X4 against Y--different output
plot(X[,"X4"],Y,main = "Correlation between X4 and Y signal", xlab = "X4 signal", ylab = "Output signal", pch = 19, col = colors[factor(group)])
#plot(X[,"X4"],Y,main = "Correlation betweeen X4 and Y signal", xlab = "X4 signal", ylab = "Output signal", col="red")

```
```{r}
#Task 2
# Calculating ones for binding the data
ones = matrix(1 , length(X)/4,1)
ones

#Model 1
#Calculating thetahat of Model 1
#Binding data from equation of model 1.
X_model1<-cbind(ones,(X[,"X4"]),(X[,"X1"])^2,(X[,"X1"])^3,(X[,"X2"])^4,(X[,"X1"])^4)
X_model1
#Calculating thetahat of model 1
Model1_thetahat=solve(t(X_model1) %*% X_model1) %*% t(X_model1) %*% Y
Model1_thetahat
```


```{r}
#Model 2
#Binding data from equation of model 2.
X_model2<-cbind(ones,(X[,"X4"]),(X[,"X1"])^3,(X[,"X3"])^4)
X_model2
#Calculating thetahat of Model 2
Model2_thetahat=solve(t(X_model2) %*% X_model2) %*% t(X_model2) %*% Y
Model2_thetahat
```


```{r}
#For model 3
#Binding data from equation of model 3.
X_model3<-cbind(ones,(X[,"X3"])^3,(X[,"X3"])^4)
X_model3
#Calculating thetahat of Model 3
Model3_thetahat=solve(t(X_model3) %*% X_model3) %*% t(X_model3) %*% Y
Model3_thetahat
```


```{r}
#For model 4
#Binding data from equation of model 4.
X_model4<-cbind(ones,X[,"X2"],X[,"X1"]^3,X[,"X3"]^4)
X_model4
#Calculating thetahat of Model 4
Model4_thetahat=solve(t(X_model4) %*% X_model4) %*% t(X_model4) %*% Y
Model4_thetahat
```


```{r}
#Binding data from equation of model 5.
X_model5<-cbind(ones,X[,"X4"],X[,"X1"]^2,X[,"X1"]^3,X[,"X3"]^4)
X_model5
#Calculating thetahat of Model 5
Model5_thetahat=solve(t(X_model5) %*% X_model5) %*% t(X_model5) %*% Y
Model5_thetahat
```


```{r}
##Task 2.2
#Calculating Y-hat and RSS Model 1
Y_hat_m1 = X_model1 %*% Model1_thetahat
Y_hat_m1
#Calculating RSS
RSS_Model_1=sum((Y-Y_hat_m1)^2)
RSS_Model_1
```
```{r}
#Calculating Y-hat and RSS of model 2
Y_hat_m2 = X_model2 %*% Model2_thetahat
Y_hat_m2
RSS_Model_2=sum((Y-Y_hat_m2)^2)
RSS_Model_2
```


```{r}
#Calculating Y-hat and RSS of model 3
Y_hat_m3 = X_model3 %*% Model3_thetahat
Y_hat_m3
RSS_Model_3=sum((Y-Y_hat_m3)^2)
RSS_Model_3
```


```{r}
#Calculating Y-hat and RSS of model 4
Y_hat_m4 = X_model4 %*% Model4_thetahat
Y_hat_m4
RSS_Model_4=sum((Y-Y_hat_m4)^2)
RSS_Model_4
```
```{r}
#Calculating Y-hat and RSS of model 5
Y_hat_m5 = X_model5 %*% Model5_thetahat
Y_hat_m5
RSS_Model_5=sum((Y-Y_hat_m5)^2)
RSS_Model_5
```


```{r}
### Task 2.3 Calculating likelihood and Variance of each model
N=length(Y)
#Calculating the Variance of Model 1
Variance_model1=RSS_Model_1/(N-1)
Variance_model1
#Calculating the log-likelihood of Model 1
likehood_Model_1=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model1))-(1/(2*Variance_model1))*RSS_Model_1
likehood_Model_1
```


```{r}
#Calculating Variance and log-likelihood of Model 2
Variance_model2=RSS_Model_2/(N-1)
Variance_model2
likehood_Model_2=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model2))-(1/(2*Variance_model2))*RSS_Model_2
likehood_Model_2
```


```{r}
#Calculating Variance and log-likelihood of Model 3
Variance_model3=RSS_Model_3/(N-1)
Variance_model3
likehood_Model_3=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model3))-(1/(2*Variance_model3))*RSS_Model_3
likehood_Model_3
```
```{r}
#Calculating Variance and log-likelihood of Model 4
Variance_model4=RSS_Model_4/(N-1)
Variance_model4
likehood_Model_4=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model4))-(1/(2*Variance_model4))*RSS_Model_4
likehood_Model_4
```
```{r}
#Calculating Variance and log-likelihood of Model 5
Variance_model5=RSS_Model_5/(N-1)
Variance_model5
likehood_Model_5=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model5))-(1/(2*Variance_model5))*RSS_Model_5
likehood_Model_5
```


```{r}
### Task 2.4 Calculating AIC And BIC of Each model
##Calculating AIC and BIC of model 1
K_model1<-length(Model1_thetahat)
K_model1
AIC_model1=2*K_model1-2*likehood_Model_1
AIC_model1
BIC_model1=K_model1*log(N)-2*likehood_Model_1
BIC_model1
```


```{r}
## thetahat of model 2
K_model2<-length(Model2_thetahat)
K_model2
##Calculating AIC and BIC of model 2
AIC_model2=2*K_model2-2*likehood_Model_2
AIC_model2
BIC_model2=K_model2*log(N)-2*likehood_Model_2
BIC_model2
```
```{r}
## thetahat of model 3
K_model3<-length(Model3_thetahat)
K_model3
##Calculating AIC and BIC of model 3
AIC_model3=2*K_model3-2*likehood_Model_3
AIC_model3
BIC_model3=K_model3*log(N)-2*likehood_Model_3
BIC_model3
```


```{r}
## thetahat of model 4
K_model4<-length(Model4_thetahat)
K_model4
##Calculating AIC and BIC of model 4
AIC_model4=2*K_model4-2*likehood_Model_4
AIC_model4
BIC_model4=K_model4*log(N)-2*likehood_Model_4
BIC_model4
```
```{r}
## thetahat of model 5
K_model5<-length(Model5_thetahat)
K_model5
##Calculating AIC and BIC of model 5
AIC_model5=2*K_model5-2*likehood_Model_5
AIC_model5
BIC_model5=K_model5*log(N)-2*likehood_Model_5
BIC_model5
```
```{r}
## Task 2.5
## Error of model1
model1_error <- Y-Y_hat_m1
## Plotting the graph QQplot and QQ line of model 1
qqnorm(model1_error, col = "darkgreen",main = "QQ plot of model 1")
qqline(model1_error, col = "blue",lwd=1.5)
```
```{r}
## Error of model2
model2_error <- Y-Y_hat_m2 # error of model 2
## Plotting QQplot and QQ line of model 2
qqnorm(model2_error, col = "royalblue",main = "QQ plot of model 2")
qqline(model2_error, col = "red", lwd=1.5)
```
```{r}
## Error of model3
model3_error <- Y- Y_hat_m3
## Plotting QQplot and QQ line of model 3
qqnorm(model3_error, col = "orange",main = "QQ plot of model 3")
qqline(model3_error, col = "darkgreen", lwd=1.5)
```
```{r}
## Error of model4
model4_error <- Y-Y_hat_m4
## Plotting QQplot and QQ line of model 4
qqnorm(model4_error, col = "#DA3778",main = "QQ plot of model 4")
qqline(model4_error, col = "#802A07", lwd=1.5)
```
```{r}
## Error of model5
model5_error <- Y- Y_hat_m5
## Plotting QQplot and QQ line of model 5
qqnorm(model5_error, col = "#807700",main = "QQ plot of model 5")
qqline(model5_error, col = "#1E276D", lwd=1.5)
```


```{r}
### Task 2.7
## Spliting the data of y into 2 form i.e. Traning and testing data set.
split_Y<-initial_split(data = as.data.frame(Y),prop=.7)

## Traning Y data split
Y_training_set<-training(split_Y)
Y_testing_set<-as.matrix(testing(split_Y))
## Testing Y data split
Y_training_data<-as.matrix(Y_training_set)
## Spliting the data of y into 2 form i.e. Traning and testing data set.
split_X<-initial_split(data = as.data.frame(X),prop=.7)
## Traning X data split
X_training_set<-training(split_X)
## Testing X data split
X_testing_set<-as.matrix(testing(split_X))
X_testing_data<-as.matrix(X_testing_set)
X_training_data<-as.matrix(X_training_set)
### Estimating model parameters using Traning set
traning_ones=matrix(1 , length(X_training_set$X1),1)
X_traning_model<-cbind(traning_ones,X_training_set[,"X2"],(X_training_set[,"X1"])^3,(X_training_set[
,"X3"])^4)
traning_thetahat=solve(t(X_traning_model) %*% X_traning_model) %*% t(X_traning_model) %*%Y_training_data
### Model out/Prediction
Y_testing_hat = X_testing_data %*% traning_thetahat
Y_testing_hat
RSS_testing=sum((Y_testing_set-Y_testing_hat)^2)
RSS_testing

t = t.test(Y_training_data, mu=500, alternative="two.sided", conf.level=0.95)
t

StandardDeviation = sqrt(Variance_model2)
data_frame_to_plot = data.frame(
  XAxis_Value = X_model2,
  YAxis_Value = Y
)
data_frame_to_plot
par(mfrow=c(2,2))

ggplot(data_frame_to_plot) +
  geom_bar( aes(x=XAxis_Value.1, y=Y), stat="identity", fill="skyblue", alpha=0.7) +
  geom_errorbar( aes(x=XAxis_Value.1, ymin=Y-StandardDeviation, ymax=Y+StandardDeviation), width=0.4, colour="orange", alpha=0.9, linewidth=1.3)

ggplot(data_frame_to_plot) +
  geom_bar( aes(x=XAxis_Value.2, y=Y), stat="identity", fill="green", alpha=0.7) +
  geom_errorbar( aes(x=XAxis_Value.2, ymin=Y-StandardDeviation, ymax=Y+StandardDeviation), width=0.4, colour="blue", alpha=0.9, linewidth=1.3)

ggplot(data_frame_to_plot) +
  geom_bar( aes(x=XAxis_Value.3, y=Y), stat="identity", fill="yellow", alpha=0.7) +
  geom_errorbar( aes(x=XAxis_Value.3, ymin=Y-StandardDeviation, ymax=Y+StandardDeviation), width=0.4, colour="red", alpha=0.9, linewidth=1.3)

ggplot(data_frame_to_plot) +
  geom_bar( aes(x=XAxis_Value.4, y=Y), stat="identity", fill="blue", alpha=0.7) +
  geom_errorbar( aes(x=XAxis_Value.4, ymin=Y-StandardDeviation, ymax=Y+StandardDeviation), width=0.4, colour="darkgreen", alpha=0.9, linewidth=1.3)

#t_test value
C_I1=-0.2695130 
C_I2=0.3805887
error_line=t$stderr

p2 <- plot(density(Y_training_data), col="#2B7A0B", lwd=2,main="Distribution of Traning Data")
abline(v=C_I1,col="#5B8FB9", lty=2, lwd=2)
abline(v=C_I2,col="#5B8FB9", lty=2, lwd=2)
abline(v=error_line,col="red",lty=2, lwd=1.5)

thetaHat_training =solve(t(X_training_data) %*% X_training_data) %*% t(X_training_data) %*%Y_training_data
thetaHat_training
length(thetaHat_training)

dis_test=density(Y_training_data)
plot((dis_test))
plot(dis_test,main = "Density plot of Y Signal")

### Calculating Confidential interval
z=1.96 ##(95%) Confidential interval
error=((Y_testing_set-Y_testing_hat))
n_len=length(Y_testing_hat)
C_I_1= z * sqrt( (error * (1-error) ) / n_len)
C_I_1
error
C_I_2= z*sqrt((error*(1+error))/n_len)
```
```{r}

#Task 3
## Model 2 will be used, parameter are selected and kept constant.
arr_1=0
arr_2=0
f_value=0
s_value=0
Model2_thetahat
#values from thetahat
thetebias <- 0.483065688 #choosen parameter
thetaone <-  0.143578928 # chosen prarameter
thetatwo <- 0.010038614 # constant value
thetafour <- 0.001912836 # constant value
Epison <- RSS_Model_2 * 2 ## fixing value of eplision
num <- 100 #number of iteration
##Calculating Y-hat for performing rejection ABC
counter <- 0
for (i in 1:num) {
range1 <- runif(1,-0.483065688,0.483065688) # calculating the range
range1
range2 <- runif(1,-0.143578928,0.143578928)
New_thetahat <- matrix(c(range1,range2,thetatwo,thetafour))
New_Y_Hat <- X_model2 %*% New_thetahat ## New Y hat
new_RSS <- sum((Y-New_Y_Hat)^2)
new_RSS
if (new_RSS > Epison){
arr_1[i] <- range1
arr_2[i] <- range2
counter = counter+1
f_value <- matrix(arr_1)
s_value <- matrix(arr_2)
}
}
hist(f_value)

hist(s_value)
###ploting the graph
plot(f_value,s_value, col = c("#FC7300", "darkgreen"), main = "Joint and Marginal Posterior Distribution", lwd=1.5)
```





